### ISSUE TITLE
ERROR: LoadError: Buffer position does not have the same length as the other buffers

### ISSUE THREAD

**Issue by Datseris** [fbanning/OSMMakie.jl#1]
I get error:
```julia
ERROR: LoadError: Buffer position does not have the same length as the other buffers.
        offset has length 2411
        position has length 1483
        scale has length 241
```
on running the script (requires `Agents#master`):
```julia
using Agents

model, zombie_step!, model_step! = Models.zombies()

using OSMMakie
using GLMakie
ac(agent) = agent.infected ? :green : :black
as(agent) = agent.infected ? 6 : 5

fig, ax, plot = osmplot(model.space.map)
display(fig)
```
The only reason for me to use `Agents` is to get the map of Geottingen. Since you have not encountered this issue so far, that's why I'm explicitly using Agents, so that we get the map that has the problem. 

Don't know if its a problem with map or some assumption of hte plotting library.

cc @fbanning , @ AayushSabharwal

**Comment by Datseris** [comment]
@AayushSabharwal  cc

**Comment by Datseris** [comment]
plotting other things on top of the plot magically makes everything dissapear.

**Comment by fbanning** [comment]
Did you use the `inspection` branch for your test?

**Comment by Datseris** [comment]
no, thanks, i'll do this when I get around to it.

**Comment by fbanning** [comment]
I'm currently working on the inspection branch again. It's almost working now, so the errors on the master branch should soon be a thing of the past. If you're not in a hurry, you can wait until I've merged it.

**Comment by fbanning** [comment]
@Datseris Should be fixed on master branch now. Feel free to try it out :)
