### ISSUE TITLE
Aspect in examples

### ISSUE THREAD

**Issue by jaakkor2** [fbanning/OSMMakie.jl#23]
Examples set `aspect = DataAspect()`. The [Gherkin building](https://en.wikipedia.org/wiki/30_St_Mary_Axe) top rightish should be a circle, not an ellipse
https://github.com/fbanning/OSMMakie-assets/blob/master/London_buildings.png

A bit better would be `autolimitaspect = 1/cosd(latitude)`.

**Comment by fbanning** [comment]
Yes, great catch and thank you for raising this issue. A while ago I've also noticed that the aspect is wrong but haven't found the time to look into aspects that are better suited for our mapping needs. I figured that DataAspect would be a simple first approach and then go from there. Will try out the autolimitaspect option you suggested (although I saw the [question you raised](https://julialang.slack.com/archives/C8RQUU2KH/p1646910863785919) on Slack about autolimitaspect which makes me wonder if it's really that nice to use) and play around with some other options. Should you find another good approach, feel free to post here.

**Comment by fbanning** [comment]
For reference, this is how OpenStreetMapXPlot.jl does it:

https://github.com/pszufe/OpenStreetMapXPlot.jl/blob/master/src/plot.jl#L39-L53

**Comment by jaakkor2** [comment]
There is `GeoAxis` from https://github.com/JuliaPlots/GeoMakie.jl that uses https://github.com/JuliaGeo/Proj4.jl that wraps https://proj.org/ .

OSMakie can plot to `GeoAxis`, but I could not find a good projection `dest = "+proj=eqearth lon_0=25"` did not show correct aspect ratio at latitude of 60 deg.  And panning and zooming acted really weird.

For now, I am fine setting `autolimitaspect` to the inverse of the cosine of the mean latitude.  This is ok when plotting small areas.
