### ISSUE TITLE
Buildings with holes

### ISSUE THREAD

**Issue by jaakkor2** [fbanning/OSMMakie.jl#24]
HM Revenue and Customs building has two holes in it
![image](https://user-images.githubusercontent.com/7318249/157553021-9f874f0b-c744-4029-8682-742817818f50.png)
and it seems to render not correctly
https://github.com/fbanning/OSMMakie-assets/blob/master/London_buildings.png
![image](https://user-images.githubusercontent.com/7318249/157553155-b247b58c-f1d4-4b5f-bd58-9b2fd5fded57.png)

**Comment by fbanning** [comment]
Ah yes, good catch. I must have forgotten to deal with inner and outer polys for the buildings.
